language: cpp
compiler:
- g++

install:
- sudo pip install codecov

os:
- linux
script:
- make -C make
- ./make/tri
- cd ./make
- ls
- gcov tri.cpp
branches:
  only:
  - master

after_success:
- codecov -X gcov
